const dotenv = require('dotenv');
const fs = require('fs');
const path = require('path');

dotenv.config({ path: path.resolve(__dirname, '../../.env') });

const apiKey = process.env.YOUTUBE_API_KEY || '';

const content = `// Auto-generated by scripts/set-env.js — do not edit manually
export const environment = {
  production: false,
  youtubeApiKey: '${apiKey}',
};
`;

const envPath = path.resolve(__dirname, '../src/environments/environment.ts');
fs.writeFileSync(envPath, content, 'utf8');

console.log(`[set-env] youtubeApiKey=${apiKey ? '***' + apiKey.slice(-4) : '(leer)'}`);
